### ISSUE TITLE
A user should be able to see log of transaction history

### ISSUE THREAD

**Issue by jasonren5** [CSE237SP2021/project-banking-app#14]
It would be good for users to be able to view a history of past transactions. This lets them review their overall usage, and potentially allows them to see evidence of foul play. Eventually, we should consider saving these to a file somewhere, where it can then be loaded upon running the program later.

I think it would be best to create a Transaction class. However, feel free to do this a different way if you think it is better. I don't think any features currently depend on an exact implmentation. However, creating a class adds the benefit of easily adding] an ArrayList<Transaction> to the Account class.

Fields for Transaction class:
- private DateTime datetime (datetime of transaction)
- private String transactionType (or, to be more robust, we should probably make this an enum of Deposit, Withdraw, Transfer, etc)
- private BigDecimal amount (amount of currency used in transaction

Methods
- public DateTime getDateTime()
- public String (or name of the enumerator) getTransactionType()
- public BigDecimal getAmount()
- constructor
  - should take in all values for all three fields

Other potential requirements
- add printTransactionHistory() to Account class
- add ArrayList<Transaction> transactionHistory to the Account class (initialize it as empty)

**Comment by cornellt** [comment]
Additional Fields:
- private BigDecimal newBalance (so that each Transaction obj can keep track of the balance at that time for printing the transactionList later)
- private String timestamp (formatted LocalDateTime String to make transactionList more readable)

Additional Methods:
- private String formatTime() (helper method called by the constructor to format a timestamp when the Transaction occurs)



I implemented an enum for transactionTypes and imported it into Account as neccesary.
